### ISSUE TITLE
TOM_TNS: Configurable author list

### ISSUE THREAD

**Issue by griffin-h** [TOMToolkit/tom_tns#7]
It would be great to allow for a user-configurable author list in the `settings.py` file. For example, I would like to make mine something like:
```
'{user_full_name}, on behalf of SAGUARO'
```
but I could also imagine the majority of users wanting to substitute a static list of names. You can see the variety of what is done [here](https://ui.adsabs.harvard.edu/search/p_=0&q=bibstem%3Atnstr&sort=date%20desc%2C%20bibcode%20desc).

The key would be to allow individual user names to be substituted in somehow, and then pass the `format`ted string to the forms on `tns_extras.py` lines 26 and 55. Probably worth considering alongside #4.

**Comment by jchate6** [comment]
It might be worth looking into including this capability as part of tom_publications.

**Comment by griffin-h** [comment]
Sorry, this was completely not clear from my initial issue, but all I'm asking about is the default author list that is prefilled in on the TNS forms. It should be a pretty simple fix of just adding one extra configuration item to the TNS block in `settings.py`.

**Comment by jchate6** [comment]
@griffin-h yes, I think we understand the immediate use case for the default author list. We probably won't get to it for a few weeks with the holidays and AAS coming up.

The above comment was more for doing this more generally with both tom_tns and other modules. 
tom_publications might be an interesting place to house this code (if not tom_base.)
The general idea would be that we could have customization author lists in different contexts that could be stored or generated for different circumstances so each app with an author list wouldn't require a different setting. This was a hasty note made during a meeting as part of a larger discussion about future development.

**Comment by jchate6** [comment]
I believe this is completed by PR #25
