### ISSUE TITLE
TOM_TNS: Only allow associating with groups of which the bot user is a member

### ISSUE THREAD

**Issue by griffin-h** [TOMToolkit/tom_tns#9]
Right now it is possible to associate your report with *any* group in the TNS. I'm not sure if the TNS will accept a report with a group that your bot is not a member of, but either way, this should not be allowed. We should restrict the list to only groups that the bot is a member of, like on the TNS web form. I'm not sure if it's possible to get this subset of groups from the TNS API. If not, the user might have to specify the list in `settings.py`.

**Comment by jchate6** [comment]
At the moment, I can't find a way to pull the group names affiliated with a specific Bot. 
You can include 'group_name' in the Broker Settings so that only the right one shows up.

**Comment by griffin-h** [comment]
Yeah I did that and it selects the correct one by default, but it looks like I can choose others as well. That's what I'm worried about.

**Comment by jchate6** [comment]
I can restrict it to only the ones listed.

**Comment by griffin-h** [comment]
That's a good idea, as long as it's possible to list more than one.

**Comment by jchate6** [comment]
@griffin-h TNS will indeed accept any reporting group regardless of Bot association. 
I cannot find any way to pull what group a bot is in from TNS, so I'll have to do this manually in `settings.py`.

Is it reasonable for the **Discovery** data source to be any group?

I'll update the settings to include a list of groups, limit the options of reporting groups to these, and make these the top choices in the discovery groups.

Sound good?

**Comment by griffin-h** [comment]
Yes I think that makes sense. I’m sure someone will later come up with some counterexample, but this is definitely a reasonable place to start. Thanks for looking into it!

On Jan 22, 2024, at 15:09, Joey Chatelain ***@***.***> wrote:


External Email


@griffin-h<https://github.com/griffin-h> TNS will indeed accept any reporting group regardless of Bot association.
I cannot find any way to pull what group a bot is in from TNS, so I'll have to do this manually in settings.py.

Is it reasonable for the Discovery data source to be any group?

I'll update the settings to include a list of groups, limit the options of reporting groups to these, and make these the top choices in the discovery groups.

Sound good?
